taskset -c 0 hyperfine -i --shell=none --runs 5 --warmup 3 -n "Optimized Version (-O3)" "./c/optimized_version.o 40"
taskset -c 0 hyperfine -i --shell=none --runs 5 --warmup 3 -n "Optimized Version (-O3 -mavx2)" "./c/optimized_version_avx.o 40"
taskset -c 0 hyperfine -i --shell=none --runs 5 --warmup 3 -n "Original Version (-O3 -mavx2)" "./c/original_version.o 40"
taskset -c 0 hyperfine -i --shell=none --runs 5 --warmup 3 -n "Casey's Version (-O3)" "./c/caseys_version.o 40"
taskset -c 0 hyperfine -i --shell=none --runs 5 --warmup 3 -n "Casey's Version (-O3 -mavx2)" "./c/caseys_version_avx.o 40"
taskset -c 0 hyperfine -i --shell=none --runs 5 --warmup 3 -n "Java Version " "java jvm/original_version 40"
taskset -c 0 hyperfine -i --shell=none --runs 5 --warmup 3 -n "Optimized Java Version" "java jvm/optimized_version 40"
